# =========================
# RabbitMQ CONFIG
# =========================

rabbitmq_host=127.0.0.1
rabbitmq_port=5672
rabbitmq_user=radius_user
rabbitmq_password=radius_pass
rabbitmq_vhost=radius
rabbitmq_exchange=radius_exchange

rabbitmq_admin_user=guest
rabbitmq_admin_password=guest