# RabbitMQ 
rabbitmq_host=127.0.0.1
rabbitmq_port=5672
rabbitmq_user=radius_user
rabbitmq_password=radius_pass
rabbitmq_vhost=radius
rabbitmq_exchange=radius_exchange

rabbitmq_admin_user=guest
rabbitmq_admin_password=guest

# MySQL
mysql_host=192.168.20.139
mysql_port=3306
mysql_user=monitor
mysql_password=xflow@123
mysql_database=MDF
mysql_schema=/root/Task-Manager-Application/scripts/schema.sql

mysql_max_open_conns=50
mysql_max_idle_conns=10
mysql_conn_max_lifetime=3600

# DB Workers
db_workers=8
db_queue_size=100000

# Partition params
partition_days=3
retention_period=45
# UTC hour, 0-23
retention_cleanup_hour=2

# Application - internal
verbosity=3
